version: "3"

tasks:
  ddb:up:
    cmds:
      - docker compose up -d

  ddb:down:
    cmds:
      - docker compose down -v

  ddb:create-tables:
    cmds:
      - bash ./infra/scripts/dynamodb/wait.sh
      - bash ./infra/scripts/dynamodb/create-tables.sh

  ddb:init:
    deps:
      - ddb:up
    cmds:
      - task: ddb:create-tables

  api:fmt:
    dir: api
    cmds:
      - uv run ruff format .

  api:lint:
    dir: api
    cmds:
      - uv run ruff check . --fix

  api:check:
    deps: [api:fmt, api:lint]

  api:test:
    dir: api
    cmds:
      - uv run pytest

  api:dev:
    dir: api
    cmds:
      - uv run uvicorn app.main:app --reload --reload-dir app